services:

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    networks:
      - helical-network
      - prometheus
    restart: unless-stopped
    ports:
      - 127.0.0.1:9090:9090
    volumes: 
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-admin-api'
    depends_on:
      - cadvisor
      - pushgateway
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: cadvisor
    networks:
    - prometheus
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  
  pushgateway:
    image: prom/pushgateway
    networks:
      - helical-network
      - prometheus
    container_name: pushgateway
    ports:
      - 127.0.0.1:9091:9091

  node-exporter:
    networks:
    - prometheus
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - 'node_exporter-data:/host:ro,rslave'
    ports:
      - 127.0.0.1:9100:9100

  grafana:
    container_name: grafana
    networks:
      - prometheus
    image: grafana/grafana-oss
    restart: unless-stopped
    ports:
     - 127.0.0.1:3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./dashboards/docker/dashboard.json:/var/lib/grafana/dashboards/docker.json
      - ./dashboards/node_exporter/dashboard.json:/var/lib/grafana/dashboards/node_exporter.json
      - ./dashboards/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./datasources/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    depends_on:
      - prometheus
      - cadvisor

volumes:
  node_exporter-data:
    driver: local

networks:
  helical-network:
    name: helical_network
    external: true
  prometheus:
    name: prometheus_network
