# reloading config: curl -X POST localhost:9090/-/reload
# this is a template, it should be edited in a prod environment
global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
  # monitoring
  - job_name: "system"
    scrape_interval: 5s
    static_configs:
      - targets: ["monitoring-prometheus:9090"]
        labels: 
          instance: "prometheus"
      - targets: ["monitoring-pushgateway:9091"]
        labels:
          instance: "pushgateway"
      - targets: ["monitoring-cadvisor:8080"]
        labels:
          instance: "cadvisor"
      - targets: ["monitoring-node-exporter:9101"]
        labels: 
          instance: "node-exporter"
  - job_name: 'otel-collector'
    # Scrape the OTel Collector service
    static_configs:
      # Note: We use the service name 'otel-collector' and the port 8889 defined in its config
      - targets: ['monitoring-otel-collector:8889']
        labels:
          instance: "otel-collector"

